GET http://localhost:3000/user

###
GET http://localhost:3000/user/idParam/typeParam

###

POST http://localhost:3000/user HTTP/1.1
content-type: application/json

{
    "firstName": "Judy",
    "lastName": "Igot",
    "email": "judigot@gmail.com",
    "password": "$2b$10$hi41dPYJv0a6NcnvrUFVqevSI5Ehxzp29yNvAkD.GXfuz98Mlt0wq",
    "createdAt": "",
    "updatedAt": ""
}
