module.exports = [
  {
    firstName: "Jude Francis",
    lastName: "Igot",
    email: "judigot@gmail.com",
    password: "$2b$10$hi41dPYJv0a6NcnvrUFVqevSI5Ehxzp29yNvAkD.GXfuz98Mlt0wq",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Judyboy",
    lastName: "Igot",
    email: "judigot1@gmail.com",
    password: "$2b$10$hi41dPYJv0a6NcnvrUFVqevSI5Ehxzp29yNvAkD.GXfuz98Mlt0wq",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Judas",
    lastName: "Igot",
    email: "judigot2@gmail.com",
    password: "$2b$10$hi41dPYJv0a6NcnvrUFVqevSI5Ehxzp29yNvAkD.GXfuz98Mlt0wq",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Hudas",
    lastName: "Igot",
    email: "judigot3@gmail.com",
    password: "$2b$10$hi41dPYJv0a6NcnvrUFVqevSI5Ehxzp29yNvAkD.GXfuz98Mlt0wq",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Torot",
    lastName: "Igot",
    email: "judigot4@gmail.com",
    password: "$2b$10$hi41dPYJv0a6NcnvrUFVqevSI5Ehxzp29yNvAkD.GXfuz98Mlt0wq",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Judigot",
    lastName: "Igot",
    email: "judigot5@gmail.com",
    password: "$2b$10$hi41dPYJv0a6NcnvrUFVqevSI5Ehxzp29yNvAkD.GXfuz98Mlt0wq",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Gwafo",
    lastName: "Igot",
    email: "judigot6@gmail.com",
    password: "$2b$10$hi41dPYJv0a6NcnvrUFVqevSI5Ehxzp29yNvAkD.GXfuz98Mlt0wq",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Jofrey",
    lastName: "Igot",
    email: "jofrey@gmail.com",
    password: "$2b$10$hi41dPYJv0a6NcnvrUFVqevSI5Ehxzp29yNvAkD.GXfuz98Mlt0wq",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Joswel",
    lastName: "Igot",
    email: "joswel@gmail.com",
    password: "$2b$10$hi41dPYJv0a6NcnvrUFVqevSI5Ehxzp29yNvAkD.GXfuz98Mlt0wq",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Julian",
    lastName: "Igot",
    email: "julian@gmail.com",
    password: "$2b$10$hi41dPYJv0a6NcnvrUFVqevSI5Ehxzp29yNvAkD.GXfuz98Mlt0wq",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
